apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: "0.24.1"  # Specify the Vault Helm chart version
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    server:
      ha:
        enabled: true
      dataStorage:
        enabled: true
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
    ui:
      enabled: true
